runtime: python312

automatic_scaling:
  max_instances: 1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
    secure: always
